### PR TITLE
`elfshaker gc`

### LINKED ISSUE #17: Implement 'elfshaker gc' to clear unneeded loose objects and packs
Assuming #15 happens, it becomes easy to delete snapshots from the loose store. This would then leave dangling objects which need deleting. Care is required during deletion though, in case someone is concurrently writing a new loose snapshot which may want to refer to those objects. So a lock is required while GC takes place.

gc doesn't make sense until you have 'rm' though, and in the meantime people can work around via manual management of pack files, and deleting the whole repository if needs be.

### PR DESCRIPTION
**Pull request by veselink1**
- [x] snapshot deduplication
- [x] object graph tracing
- [x] fs-based lock 
- [x] performance improvements (`compute_snapshot_checksums` is around 96% CPU time) 
- [x] API design
- [x] Documentation

Closes #17

### CODE REVIEW

**Comment by peterwaller-arm** [comment]
Nice!

Maybe you saw it, github recently wrote an article about git's GC. https://github.blog/2022-09-13-scaling-gits-garbage-collection/ Worth a read in case it inspires anything in you.

I'd appreciate a brief high level description (perhaps a source code comment?) of what GC aims to do and how it is achieved it (and if there are any gotchas, or things you do to avoid gotchas). I guess the main thing in my mind is to cope with the case where you potentially have multiple elfshaker processes sharing the elfshaker_data directory, for which I guess "fs-based lock" on your checklist will be the most straightforward answer.

For the performance issue of detecting identical snapshots, I'd like to see us add a field which indicates the snapshot hash to the index.

**Comment by veselink1** [comment]
> Maybe you saw it, github recently wrote an article about git's GC.

I had not seen this, thanks.

> I'd appreciate a brief high level description

Sure, it's still WIP. I've not identified any gotchas, but our case is simpler than git.

> I'd like to see us add a field which indicates the snapshot hash to the index.

I think that's a very good idea. We already had a few other changes to consider for 1.0 (file permissions and UTF-8/cross-platform file paths). There are however ways to speed up compute_snapshot_checksums

**Comment by veselink1** [comment]
Ping for code review. 

> I'd appreciate a brief high level description (perhaps a source code comment?)

I've just added some more detailed descriptions of how GC is implemented in `gc.rs`, doc comments and commit message.

> and if there are any gotchas, or things you do to avoid gotchas

None that I can think of. But then again maybe you will find some holes in the approach/implementation :) 

> I guess the main thing in my mind is to cope with the case where you potentially have multiple elfshaker processes 

I think I've managed to handle that nicely -- Repository::open takes a shared file-based lock on the directory, and that gets upgraded to an exclusive lock when we need to delete stuff (so no elfshaker store/pack could be in progress while we're doing this).

**Comment by Mistuke** [comment]
Hi, question about the default behavior. so if I just do `elfshaker gc` does it actually do anything? or must I always specify an action `-s` , `-o` etc? I can't seem to make out from the docs or help.

**Comment by veselink1** [comment]
@Mistuke 
`elfshaker gc` without options should output
```
[ERROR (main) 1.092µs]: Specify what to GC (--loose-snapshots, --loose-objects). Nothing to do!
[ERROR (main) 33.774µs]: *FATAL*: Invalid options!
```

**Comment by Mistuke** [comment]
@veselink1 thanks for this! `gc` is working great :)

**Comment by peterwaller-arm** [comment]
Thanks for your patience, and thanks for testing @Mistuke!

**Pull request merged**
